### ISSUE TITLE
Adding ACL through a factory-object

### ISSUE THREAD

**Issue by peletiah** [wichert/rest_toolkit#18]
This project looks very promising, I really like the effort you put into a proper and thorough documentation!

I'm looking into using this together with [ziggurat foundations](https://github.com/ergo/ziggurat_foundations) and I have a basic question about permissions:

Can I add an ACL defined in a factory-object to an REST resource, analogous to the factory-argument in [pyramid.config.Configurator.add_route](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator.add_route)?

**Comment by wichert** [comment]
You don't need to: the resource itself is the context. What you will need to do is put the `__acl__` on the resource itself, as you can see in the [security chapter](http://rest-toolkit.readthedocs.io/en/latest/security.html) of the documentation.
